# Alacritty Configuration - Fixed for TUI Arrow Key Navigation

[env]
TERM = "xterm-256color"

[window]
opacity = 1.0
decorations = "full"

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

# Fira Code doesn't have true italic, so we'll use regular with synthetic italic
[font.italic]
family = "Fira Code"
style = "Regular"

[font.bold_italic]
family = "Fira Code"
style = "Bold"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

# Key bindings - ONLY bind keys with modifiers to avoid interfering with TUI apps
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "SpawnNewInstance"

# Scrolling with Shift + Arrow keys (won't interfere with TUI)
[[keyboard.bindings]]
key = "Up"
mods = "Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "Down"
mods = "Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"

# Font size adjustment
[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

# DO NOT bind plain arrow keys - leave them free for TUI applications
# These would break TUI navigation:
# [[keyboard.bindings]]
# key = "Up"
# action = "..."

[selection]
save_to_clipboard = true
