---
name: my-xmonad
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - xmonad
  - xmonad-contrib
  - containers
executables:
  my-xmonad:
    main: xmonad.hs
    source-dirs:
      - .
      - lib
    ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N]
