return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "lua-language-server",
      "stylua",
      "ocaml-lsp",
      "ocaml-format",
      "astro-language-server",
      "bash-language-server",
      "actionlint",
      "commitlint",
      "diagnostic-languageserver",
      "html-lsp",
      "svelte-language-server",
      "dockerfile-language-server",
      "docker-compose-language-server",
      "jsonlint",
      "nginx-language-server",
      "jsonls",
      "purescript-language-server",
      "purescript-tidy",
      "haskell-language-server",
      "yaml-language-server",
      "ts_ls",
      "eslint-lsp",
      "css-lsp",
      "cssmodules-language-server",
      "css-variables-language-server",
      "gitlint",
      "angular-language-server",
      "eslint_d",
      "prettier",
      "prettierd",
    },
  },
}
