return {
  "stevearc/conform.nvim",
  event = { "BufWritePre" },
  cmd = { "ConformInfo" },
  opts = {
    formatters_by_ft = {
      nix = { "nixpkgs-fmt" },
      lua = { "luaformatter", "stylua", stop_after_first = true },
      css = { "prettierd", stop_after_first = true },
      elm = { "elm_format", stop_after_first = true },
      ocaml = { "ocamlformat", stop_after_first = true },
      yaml = { "yamlfix", stop_after_first = true },
      markdown = { "mdformat", stop_after_first = true },
      haskell = { "ormolu", stop_after_first = true },
      html = { "prettierd", "prettier", "biome", stop_after_first = true },
      typescript = { "eslint_d", "dprint", "prettierd", "biome", stop_after_first = true },
      javascript = { "eslint_d", "dprint", "prettierd", "biome", stop_after_first = true },
      typescriptreact = { "prettierd", "biome", stop_after_first = true },
      json = { "eslint_d", "prettierd" },
      javascriptreact = { "prettierd", "biome", stop_after_first = true },
      purescript = { "purs-tidy", stop_after_first = true },
      luals = { "stylua", stop_after_first = true },
      ["_"] = { "trim_whitespace", stop_after_first = true },
    },
    format_on_save = {
      timeout_ms = 500,
      lsp_format = "fallback",
    },
  },
}
