return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPost", "BufNewFile" },
  build = ":TSUpdate",
  main = "nvim-treesitter.configs",
  opts = {
    highlight = { enable = true },
    ensure_installed = {
      "purescript",
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "typescript",
      "javascript",
      "haskell",
      "json",
      "yaml",
      "markdown",
      "markdown_inline",
      "bash",
      "tsx",
      "python",
      "rust",
      "go",
    },
  },
}
