return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ignore_install = {},
    ensure_installed = {
      "vim",
      "lua",
      "vimdoc",
      "html",
      "css",
      "typescript",
      "javascript",
      "haskell",
      "json",
      "yaml",
      "markdown",
      "markdown_inline",
      "bash",
      "tsx",
      "python",
      "rust",
      "go",
    },
  },
}
